import Head from "next/head"
import Image from "next/image"
import { Inter } from "@next/font/google"
import styles from "../styles/Home.module.css"
import React from "react"

const inter = Inter({ subsets: ["latin"] })

const colors = [
  "black",
  "red",
  "orange",
  "yellow",
  "chartreuse",
  "green",
  "cyan",
  "blue",
  "indigo",
  "violet",
  "white",
]

const pi =
  "14159265358979323846264338327950288419716939937510582097494459230781640628620899862803482534211706798214808651328230664709384460955058223172535940812848111745028410270193852110555964462294895493038196442881097566593344612847564823378678316527120190914564856692346034861045432664821339360726024914127372458700660631558817488152092096282925409171536436789259036001133053054882046652138414695194151160943305727036575959195309218611738193261179310511854807446237996274956735188575272489122793818301194912983367336244065664308602139494639522473719070217986094370277053921717629317675238467481846766940513200056812714526356082778577134275778960917363717872146844090122495343014654958537105079227968925892354201995611212902196086403441815981362977477130996051870721134999999837297804995105973173281609631859502445945534690830264252230825334468503526193118817101000313783875288658753320838142061717766914730359825349042875546873115956286388235378759375195778185778053217122680661300192787661119590921642019893809525720106548586327886593615338182796823030195203530185296899577362259941389124972177528347913151557485724245415069595082953311686172785588907509838175463746493931925506040092770167"

const getCosSin = (_deg): number[] => {
  const r = 50
  const rCos = r * Math.cos((_deg * Math.PI) / 180)
  const rSin = r * Math.sin((_deg * Math.PI) / 180)
  return [rCos, rSin]
}

const drawLine = (_ctx, _num, _x1, _y1): number[] => {
  _ctx.beginPath()
  _ctx.moveTo(_x1, _y1)
  const r = 50
  let newPos
  if (_num == 0) {
    newPos = [_x1, _y1 - getCosSin(90)[1]]
    _ctx.lineTo(newPos[0], newPos[1])
  } else if (_num == 1) {
    const cosSin = getCosSin(54)
    newPos = [_x1 + cosSin[0], _y1 - cosSin[1]]
    _ctx.lineTo(newPos[0], newPos[1])
  } else if (_num == 2) {
    const cosSin = getCosSin(18)
    newPos = [_x1 + cosSin[0], _y1 - cosSin[1]]
    _ctx.lineTo(newPos[0], newPos[1])
  } else if (_num == 3) {
    const cosSin = getCosSin(342)
    newPos = [_x1 + cosSin[0], _y1 - cosSin[1]]
    _ctx.lineTo(newPos[0], newPos[1])
  } else if (_num == 4) {
    const cosSin = getCosSin(306)
    newPos = [_x1 + cosSin[0], _y1 - cosSin[1]]
    _ctx.lineTo(newPos[0], newPos[1])
  } else if (_num == 5) {
    const cosSin = getCosSin(270)
    newPos = [_x1, _y1 - cosSin[1]]
    _ctx.lineTo(newPos[0], newPos[1])
  } else if (_num == 6) {
    const cosSin = getCosSin(234)
    newPos = [_x1 + cosSin[0], _y1 - cosSin[1]]
    _ctx.lineTo(newPos[0], newPos[1])
  } else if (_num == 7) {
    const cosSin = getCosSin(198)
    newPos = [_x1 + cosSin[0], _y1 - cosSin[1]]
    _ctx.lineTo(newPos[0], newPos[1])
  } else if (_num == 8) {
    const cosSin = getCosSin(162)
    newPos = [_x1 + cosSin[0], _y1 - cosSin[1]]
    _ctx.lineTo(newPos[0], newPos[1])
  } else if (_num == 9) {
    const cosSin = getCosSin(126)
    newPos = [_x1 + cosSin[0], _y1 - cosSin[1]]
    _ctx.lineTo(newPos[0], newPos[1])
  }

  _ctx.stroke()
  return newPos
}

export default function Home() {
  React.useEffect(() => {
    const canvas = document.getElementById("canvas")
    const ctx = canvas.getContext("2d")

    // background coloring
    ctx.fillStyle = "white"
    ctx.fillRect(0, 0, canvas.width, canvas.height)

    ctx.lineWidth = 2
    let newPos = [400, 2500]
    for (let i = 0; i < 1000; i++) {
      newPos = drawLine(ctx, pi[i], newPos[0], newPos[1])
    }
  }, [])

  return (
    <>
      <Head>
        <title>Title</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <canvas id="canvas" width="3000" height="3000"></canvas>
      </main>
    </>
  )
  /*
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.tsx</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{" "}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image src="/thirteen.svg" alt="13" width={40} height={31} priority />
          </div>
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Learn <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Templates <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main>
    </>
  )
  */
}
