import Head from "next/head"
import Image from "next/image"
import { Inter } from "@next/font/google"
import styles from "../styles/Home.module.css"
import React from "react"

const inter = Inter({ subsets: ["latin"] })

const colors = [
  "black",
  "red",
  "orange",
  "yellow",
  "chartreuse",
  "green",
  "cyan",
  "blue",
  "indigo",
  "violet",
  "white",
]

const pi = "14159265358979323846"

const getCosSin = (_deg): number[] => {
  const r = 50
  const rCos = r * Math.cos((_deg * Math.PI) / 180)
  const rSin = r * Math.sin((_deg * Math.PI) / 180)
  return [rCos, rSin]
}

const drawLine = (_ctx, _num, _x1, _y1): number[] => {
  _ctx.beginPath()
  _ctx.moveTo(_x1, _y1)
  const r = 50
  let newPos
  if (_num == 0) {
    newPos = [_x1, _y1 - getCosSin(90)[1]]
    _ctx.lineTo(newPos[0], newPos[1])
  } else if (_num == 1) {
    const cosSin = getCosSin(54)
    newPos = [_x1 + cosSin[0], _y1 - cosSin[1]]
    _ctx.lineTo(newPos[0], newPos[1])
  } else if (_num == 2) {
    const cosSin = getCosSin(18)
    newPos = [_x1 + cosSin[0], _y1 - cosSin[1]]
    _ctx.lineTo(newPos[0], newPos[1])
  } else if (_num == 3) {
    const cosSin = getCosSin(342)
    newPos = [_x1 + cosSin[0], _y1 - cosSin[1]]
    _ctx.lineTo(newPos[0], newPos[1])
  } else if (_num == 4) {
    const cosSin = getCosSin(306)
    newPos = [_x1 + cosSin[0], _y1 - cosSin[1]]
    _ctx.lineTo(newPos[0], newPos[1])
  } else if (_num == 5) {
    const cosSin = getCosSin(270)
    newPos = [_x1, _y1 - cosSin[1]]
    _ctx.lineTo(newPos[0], newPos[1])
  } else if (_num == 6) {
    const cosSin = getCosSin(234)
    newPos = [_x1 + cosSin[0], _y1 - cosSin[1]]
    _ctx.lineTo(newPos[0], newPos[1])
  } else if (_num == 7) {
    const cosSin = getCosSin(198)
    newPos = [_x1 + cosSin[0], _y1 - cosSin[1]]
    _ctx.lineTo(newPos[0], newPos[1])
  } else if (_num == 8) {
    const cosSin = getCosSin(162)
    newPos = [_x1 + cosSin[0], _y1 - cosSin[1]]
    _ctx.lineTo(newPos[0], newPos[1])
  } else if (_num == 9) {
    const cosSin = getCosSin(126)
    newPos = [_x1 + cosSin[0], _y1 - cosSin[1]]
    _ctx.lineTo(newPos[0], newPos[1])
  }

  _ctx.stroke()
  return newPos
}

export default function Home() {
  React.useEffect(() => {
    const canvas = document.getElementById("canvas")
    const ctx = canvas.getContext("2d")
    /*for (let i = 0; i < pi.length; i++) {
      
      }*/

    ctx.lineWidth = 5
    let newPos = [500, 500]
    for (let i = 0; i < 10; i++) {
      newPos = drawLine(ctx, i, newPos[0], newPos[1])
    }
  }, [])

  return (
    <>
      <Head>
        <title>Title</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <canvas id="canvas" width="1000" height="1000"></canvas>
      </main>
    </>
  )
  /*
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.tsx</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{" "}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image src="/thirteen.svg" alt="13" width={40} height={31} priority />
          </div>
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Learn <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Templates <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main>
    </>
  )
  */
}
