import Head from "next/head"
import Image from "next/image"
import { Inter } from "@next/font/google"
import styles from "../styles/Home.module.css"
import React from "react"

const inter = Inter({ subsets: ["latin"] })

const colors = [
  "black",
  "red",
  "orange",
  "yellow",
  "chartreuse",
  "green",
  "cyan",
  "blue",
  "indigo",
  "violet",
  "white",
]

const pi = "14159265358979323846"

export default function Home() {
  React.useEffect(() => {
    const canvas = document.getElementById("canvas")
    const ctx = canvas.getContext("2d")
    const r = 50
    /*for (let i = 0; i < pi.length; i++) {
      
      }*/

    ctx.lineWidth = 5

    ctx.beginPath()
    ctx.moveTo(500, 500)
    ctx.lineTo(547.55, 484.55) // (+47.55, -15.45)
    ctx.moveTo(500, 500)
    ctx.lineTo(484.55, 547.55) // (-15.45, +47.55)
    ctx.moveTo(500, 500)
    ctx.lineTo(547.55, 515.45) // (+47.55, +15.45)
    ctx.moveTo(500, 500)
    ctx.lineTo(529.39, 459.55) // (+29.39, -40.45)

    //ctx.lineTo(500 + r * Math.cos(0.2 * Math.PI), 500 + r * Math.sin(0.2 * Math.PI))
    ctx.strokeStyle = "#824302"
    ctx.stroke()

    /*ctx.beginPath()
    ctx.moveTo(0, 50)
    ctx.lineTo(50, 50)
    ctx.strokeStyle = "#473922"
    ctx.stroke()*/

    ctx.beginPath()
    ctx.moveTo(95, 25)
    ctx.lineTo(150, 80)
    ctx.lineTo(205, 25)
    ctx.lineTo(210, 130)
    ctx.strokeStyle = "#fd4302"
    ctx.lineWidth = 10
    ctx.stroke()
  }, [])

  return (
    <>
      <Head>
        <title>Title</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <canvas id="canvas" width="1000" height="1000"></canvas>
      </main>
    </>
  )
  /*
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.tsx</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{" "}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image src="/thirteen.svg" alt="13" width={40} height={31} priority />
          </div>
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Learn <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Templates <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main>
    </>
  )
  */
}
